sonar.projectKey=fiap-solid-link_fiap-ong-esperanca-identity-api
sonar.projectName=fiap-ong-esperanca-identity-api
sonar.organization=fiap-solid-link

sonar.sources=src
sonar.tests=test
sonar.cs.opencover.reportsPaths=**/TestResults/**/coverage.opencover.xml
sonar.coverage.exclusions=**/*Program.cs,**/*Startup.cs,**/*Migrations/**,**/*test/**
sonar.qualitygate.wait=true