apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-api-config
  namespace: esperanca
data:
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_ENVIRONMENT: "Development"
  Jwt__Issuer: "esperanca-identity-api"
  Jwt__Audience: "esperanca-platform"
  Jwt__AccessTokenExpirationMinutes: "30"
